version: '3'
services:
  # PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kerjapraktik_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - kerjapraktik_network

  # MySQL Service
  db:
    image: mysql:8.0
    container_name: kerjapraktik_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - kerjapraktik_network

  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: kerjapraktik_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - kerjapraktik_network

networks:
  kerjapraktik_network:
    driver: bridge

volumes:
  dbdata:
    driver: local
